site_name: pogo
site_description: Dataset-agnostic generative BI for biologists
site_url: https://vincentclaes.github.io/pogo/
repo_url: https://github.com/vincentclaes/pogo
repo_name: vincentclaes/pogo

docs_dir: docs
use_directory_urls: false

nav:
  - Home: index.md
  - Introduction (Human): introduction_human.md
  - Introduction (Machine): introduction_machine.md
  - Plan: plan.md
  - Testing: testing.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - search.suggest
    - content.code.copy

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.snippets:
      check_paths: true
